server:
  port: 8080

spring:
  swagger:
    enable: true
  druid:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/spring-template?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true}
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:Zp18716331455}
    login-username: admin
    login-password: 123
    allow: 127.0.0.1
  redis:
    host: ${REDIS_HOST:10.12.2.64}
    password: ${REDIS_PASSWORD:sy_202106}
    port: 6379

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: env,health,info