server:
  port: 8080

spring:
  swagger:
    enable: true
  druid:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/spring-template?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true}
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:Zp18716331455}
    login-username: admin
    login-password: 123
    allow: 127.0.0.1
  redis:
    host: ${REDIS_HOST:10.12.2.64}
    password: ${REDIS_PASSWORD:sy_202106}
    port: 6379
  kafka:
    # 指定kafka server的地址，集群配多个，中间，逗号隔开
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:10.15.2.214:9092,10.15.2.215:9092,10.15.2.216:9092}
    # 指定默认消费者group id --> 由于在kafka中，同一组中的consumer不会读取到同一个消息，依靠groud.id设置组名
    consumer:
      group-id: spring-web-dev

seaweedfs:
  host: 10.15.2.53
  port: 9333
  use-public: true

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: env,health,info

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Kafka Topic
app.topic.test_record: TEST-RECORD-DEV
