server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  banner:
    location: banner.txt
  profiles:
    active: ${ENV_TYPE:dev}
  mvc:
    async:
      request-timeout: 600000
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 100MB
      # 总上传文件大小
      max-request-size: 500MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  swagger:
    groupName: spring-web
    basePackage: com.self
    version: 1.0.0
    title: spring-web
    description: spring-web 开发文档
    contactName: zp
    contactEmail: default@default.com
    contactUrl: www.default.com

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*.xml

logging:
  config: ${LOGING_CONFIG:classpath:logback/logback-test.xml}
  level:
    root: info