server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  banner:
    location: banner.txt
  profiles:
    active: ${ENV_TYPE:dev}
  mvc:
    async:
      request-timeout: 600000
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 100MB
      # 总上传文件大小
      max-request-size: 500MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  config: ${LOGING_CONFIG:classpath:logback/logback-test.xml}
  level:
    root: info